aliases:
  validate_dependencies_step: &validate_dependencies_step
    run:
      name: Validate Dependencies
      command: yarn install --immutable --immutable-cache

  unit_test: &unit_test
    steps:
      - checkout
      - *validate_dependencies_step
      - run:
          name: Run Tests
          command: 'yarn jest --ci'

version: 2
jobs:
  node-v10-latest:
    docker:
      - image: circleci/node:10
    <<: *unit_test
  node-v12-latest:
    docker:
      - image: circleci/node:12
    <<: *unit_test
  node-v13-latest:
    docker:
      - image: circleci/node:13
    <<: *unit_test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *validate_dependencies_step
      - run:
          name: Publish package
          command: npx semantic-release

workflows:
  version: 2
  test-deploy:
    jobs:
      - node-v10-latest
      - node-v12-latest
      - node-v13-latest
      - deploy:
          requires:
            - node-v10-latest
            - node-v12-latest
            - node-v13-latest
          filters:
            branches:
              only: master
