#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}/.."

rm -rf build

echo "Building CommonJS…"
npx tsc --module commonjs
for file in build/*.js; do
  mv "${file}" "${file%.js}.cjs"
done

echo "Building ESM…"
npx tsc --module esnext
for file in build/*.js; do
  mv "${file}" "${file%.js}.mjs"
done
